Repository astrolabsoftware/spark3D, pull requests merged in 2018-07, with the labels that each got.

#61 Update paths with new groupID coordinates (theastrolab)
  CHANGELOG.md
  README.md
  docs/01_installation.md
  docs/02_introduction.md
  docs/03_partitioning.md
  docs/04_query.md
  docs/05_visualization.md
  docs/about.md
  run_scala.sh
  run_xmatch_cluster.sh
Labels: maven central

#64 Uniform sphere API
  docs/02_introduction.md
  src/main/scala/com/spark3d/spatial3DRDD/Loader.scala
  src/main/scala/com/spark3d/spatial3DRDD/Point3DRDD.scala
  src/main/scala/com/spark3d/spatial3DRDD/SphereRDD.scala
  src/test/resources/cartesian_spheres.json
  src/test/resources/cartesian_spheres.txt
  src/test/scala/com/spark3d/spatial3DRDD/LoaderTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/SphereRDDTest.scala
  src/test/scala/com/spark3d/spatialOperator/SpatialQueryTest.scala
Labels: 3DRDD, API

#65 Redirect link to new org URL
  docs/01_installation.md
  docs/02_introduction.md
  docs/03_partitioning.md
  docs/04_query.md
  docs/05_visualization.md
  docs/_config.yml
  docs/_pages/home.md
  docs/about.md
Labels: website

#62 Added a KNNEfficient implementation with takeOrdered
  src/main/scala/com/spark3d/geometryObjects/Shape3D.scala
  src/main/scala/com/spark3d/spatial3DRDD/Shape3DRDD.scala
  src/main/scala/com/spark3d/spatialOperator/SpatialQuery.scala
  src/main/scala/com/spark3d/spatialPartitioning/Octree.scala
  src/main/scala/com/spark3d/spatialPartitioning/OctreePartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/OnionPartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/OnionPartitioning.scala
  src/main/scala/com/spark3d/spatialPartitioning/SpatialPartitioner.scala
  src/test/scala/com/spark3d/spatial3DRDD/SphereRDDTest.scala
  src/test/scala/com/spark3d/spatialOperator/SpatialQueryTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreePartitionerTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreeTest.scala
Labels: 3D methods, Partitioning

#66 Package name
  CHANGELOG.md
  README.md
  build.sbt
  docs/01_installation.md
  docs/02_introduction.md
  docs/03_partitioning.md
  docs/04_query.md
  docs/_pages/home.md
  examples/jupyter/CrossMatch.ipynb
  examples/jupyter/onion_partitioning.ipynb
  run_scala.sh
  run_xmatch_cluster.sh
  src/main/scala/com/spark3d/examples/CrossMatch.scala
  src/main/scala/com/spark3d/examples/OnionSpace.scala
  src/main/scala/com/spark3d/geometryObjects/BoxEnvelope.scala
  src/main/scala/com/spark3d/geometryObjects/Point3D.scala
  src/main/scala/com/spark3d/geometryObjects/Shape3D.scala
  src/main/scala/com/spark3d/geometryObjects/ShellEnvelope.scala
  src/main/scala/com/spark3d/indexingMethods/HealpixIndexing.scala
  src/main/scala/com/spark3d/serialization/Spark3dRegistrator.scala
  src/main/scala/com/spark3d/spatial3DRDD/Loader.scala
  src/main/scala/com/spark3d/spatial3DRDD/Point3DRDD.scala
  src/main/scala/com/spark3d/spatial3DRDD/Shape3DRDD.scala
  src/main/scala/com/spark3d/spatial3DRDD/SphereRDD.scala
  src/main/scala/com/spark3d/spatialOperator/CenterCrossMatch.scala
  src/main/scala/com/spark3d/spatialOperator/PixelCrossMatch.scala
  src/main/scala/com/spark3d/spatialOperator/RangeQuery.scala
  src/main/scala/com/spark3d/spatialOperator/SpatialQuery.scala
  src/main/scala/com/spark3d/spatialPartitioning/Octree.scala
  src/main/scala/com/spark3d/spatialPartitioning/OctreePartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/OctreePartitioning.scala
  src/main/scala/com/spark3d/spatialPartitioning/OnionPartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/OnionPartitioning.scala
  src/main/scala/com/spark3d/spatialPartitioning/SpatialPartitioner.scala
  src/main/scala/com/spark3d/utils/ExtPointing.scala
  src/main/scala/com/spark3d/utils/GeometryObjectComparator.scala
  src/main/scala/com/spark3d/utils/GridType.scala
  src/main/scala/com/spark3d/utils/Utils.scala
  src/test/scala/com/spark3d/geometryObjects/BoxEnvelopeTest.scala
  src/test/scala/com/spark3d/geometryObjects/Point3DTest.scala
  src/test/scala/com/spark3d/geometryObjects/Shape3DTest.scala
  src/test/scala/com/spark3d/geometryObjects/ShellEnvelopeTest.scala
  src/test/scala/com/spark3d/serialization/Spark3dRegistratorTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/LoaderTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/Point3DRDDTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/SphereRDDTest.scala
  src/test/scala/com/spark3d/spatialOperator/CenterCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/PixelCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/RangeQueryTest.scala
  src/test/scala/com/spark3d/spatialOperator/SpatialQueryTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreePartitionerTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreeTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OnionPartitionerTest.scala
  src/test/scala/com/spark3d/utils/GridTypeTest.scala
  src/test/scala/com/spark3d/utils/UtilsTest.scala
Labels: API, documentation, maven central, version

#67 Octree and Geometry Objects Bug Fixes
  src/main/scala/com/spark3d/geometryObjects/BoxEnvelope.scala
  src/main/scala/com/spark3d/spatialPartitioning/Octree.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreePartitionerTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreeTest.scala
Labels: 3D methods, bug

#69 Unify the IO: One constructor to rule them all!
  docs/01_installation.md
  docs/02_introduction.md
  docs/03_partitioning.md
  docs/04_query.md
  src/main/scala/com/spark3d/examples/CrossMatch.scala
  src/main/scala/com/spark3d/examples/OnionSpace.scala
  src/main/scala/com/spark3d/spatial3DRDD/Loader.scala
  src/main/scala/com/spark3d/spatial3DRDD/Point3DRDD.scala
  src/main/scala/com/spark3d/spatial3DRDD/SphereRDD.scala
  src/test/scala/com/spark3d/geometryObjects/ShellEnvelopeTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/LoaderTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/Point3DRDDTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/SphereRDDTest.scala
  src/test/scala/com/spark3d/spatialOperator/CenterCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/PixelCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/RangeQueryTest.scala
  src/test/scala/com/spark3d/spatialOperator/SpatialQueryTest.scala
Labels: 3DRDD, API

#70 Bump version to v0.1.4
  CHANGELOG.md
  README.md
  build.sbt
  docs/01_installation.md
  docs/02_introduction.md
  docs/04_query.md
  docs/_pages/home.md
  docs/about.md
  examples/jupyter/CrossMatch.ipynb
  examples/jupyter/onion_partitioning.ipynb
  run_scala.sh
  run_xmatch_cluster.sh
Labels: version

#76 fix for elements missing after repartitioning RDD with Octree Partitioner
  src/main/scala/com/spark3d/geometryObjects/BoxEnvelope.scala
  src/main/scala/com/spark3d/spatial3DRDD/Shape3DRDD.scala
  src/test/scala/com/spark3d/spatial3DRDD/SphereRDDTest.scala
Labels: Partitioning, bug

#81 Allow user to cache the rawRDD while loading data to speed-up re-partitioning.
  docs/02_introduction.md
  docs/03_partitioning.md
  src/main/scala/com/spark3d/examples/Partitioning.scala
  src/main/scala/com/spark3d/spatial3DRDD/Point3DRDD.scala
  src/main/scala/com/spark3d/spatial3DRDD/Shape3DRDD.scala
  src/main/scala/com/spark3d/spatial3DRDD/SphereRDD.scala
  src/test/scala/com/spark3d/spatial3DRDD/Point3DRDDTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/SphereRDDTest.scala
Labels: Partitioning, performance

#83 0.1.5
  .gitignore
  CHANGELOG.md
  README.md
  build.sbt
  docs/01_installation.md
  docs/_config.yml
  docs/_pages/home.md
  docs/about.md
  examples/jupyter/CrossMatch.ipynb
  examples/jupyter/onion_partitioning.ipynb
  examples/jupyter/windowQuery.ipynb
  pic/spark3d_lib_0.1.5.png
  runners/README.md
  runners/benchmark_knn.sh
  runners/run_knn.sh
  runners/run_knnGeo.sh
  runners/run_part.sh
  runners/run_scala.sh
  runners/run_shuffle.sh
  runners/run_xmatch.sh
  runners/run_xmatch_cluster.sh
  runners/run_xmatch_geo.sh
Labels: version
