Repository astrolabsoftware/spark3D, pull requests merged in 2018-06, with the labels that each got.

#24 Add new objects and routines to perform the cross-match of 2 data sets.
  examples/jupyter/CcrossmatchAxB.png
  examples/jupyter/CcrossmatchAxBOnly.png
  examples/jupyter/CrossMatch.ipynb
  examples/jupyter/crossmatchAxB.png
  examples/jupyter/crossmatchAxBOnly.png
  examples/jupyter/crossmatch_neighbours.jpg
  examples/jupyter/crossmatch_sphere.jpg
  examples/jupyter/line.png
  src/main/scala/com/spark3d/geometryObjects/Point3D.scala
  src/main/scala/com/spark3d/geometryObjects/Shape3D.scala
  src/main/scala/com/spark3d/spatial3DRDD/Shape3DRDD.scala
  src/main/scala/com/spark3d/spatialOperator/CenterCrossMatch.scala
  src/main/scala/com/spark3d/spatialOperator/PixelCrossMatch.scala
  src/test/resources/astro_obs2.fits
  src/test/resources/astro_obs_A_light.fits
  src/test/resources/astro_obs_B_light.fits
  src/test/scala/com/spark3d/geometryObjects/Point3DTest.scala
  src/test/scala/com/spark3d/geometryObjects/Shape3DTest.scala
  src/test/scala/com/spark3d/spatial3DRDD/Point3DRDDTest.scala
  src/test/scala/com/spark3d/spatialOperator/CenterCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/PixelCrossMatchTest.scala
Labels: 3D methods

#29 Write the partitioner in the spirit of Scala (no more Java-like)
  src/main/scala/com/spark3d/spatial3DRDD/Shape3DRDD.scala
  src/main/scala/com/spark3d/spatialOperator/CenterCrossMatch.scala
  src/main/scala/com/spark3d/spatialOperator/PixelCrossMatch.scala
  src/main/scala/com/spark3d/spatialPartitioning/OnionPartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/SpatialPartitioner.scala
  src/test/scala/com/spark3d/spatialOperator/CenterCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/PixelCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OnionPartitionerTest.scala
Labels: language

#30 Octree
  src/main/scala/com/spark3d/geometry/BoxEnvelope.scala
  src/main/scala/com/spark3d/geometryObjects/Point3D.scala
  src/main/scala/com/spark3d/geometryObjects/Shape3D.scala
  src/main/scala/com/spark3d/geometryObjects/Sphere.scala
  src/main/scala/com/spark3d/spatialPartitioning/Octree.scala
  src/main/scala/com/spark3d/spatialPartitioning/OctreePartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/OctreePartitioning.scala
  src/test/scala/com/spark3d/geometry/ShellEnvelopeTest.scala
  src/test/scala/com/spark3d/geometryObjects/Point3DTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreePartitionerTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreeTest.scala
Labels: Partitioning

#31 Kryo
  run_xmatch_cluster.sh
  src/main/scala/com/spark3d/examples/CrossMatch.scala
  src/main/scala/com/spark3d/serialization/Spark3dRegistrator.scala
  src/test/scala/com/spark3d/serialization/Spark3dRegistratorTest.scala
Labels: serializer

#40 Code refactoring: Replace Sphere by ShellEnvelope, Shape3D heritage, and move everything under geometryObjects
  src/main/scala/com/spark3d/geometry/Envelope.scala
  src/main/scala/com/spark3d/geometryObjects/BoxEnvelope.scala
  src/main/scala/com/spark3d/geometryObjects/Point3D.scala
  src/main/scala/com/spark3d/geometryObjects/Shape3D.scala
  src/main/scala/com/spark3d/geometryObjects/ShellEnvelope.scala
  src/main/scala/com/spark3d/geometryObjects/Sphere.scala
  src/main/scala/com/spark3d/serialization/Spark3dRegistrator.scala
  src/main/scala/com/spark3d/spatial3DRDD/Shape3DRDD.scala
  src/main/scala/com/spark3d/spatial3DRDD/SphereRDD.scala
  src/main/scala/com/spark3d/spatialPartitioning/Octree.scala
  src/main/scala/com/spark3d/spatialPartitioning/OctreePartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/OctreePartitioning.scala
  src/main/scala/com/spark3d/spatialPartitioning/OnionPartitioner.scala
  src/main/scala/com/spark3d/spatialPartitioning/OnionPartitioning.scala
  src/main/scala/com/spark3d/spatialPartitioning/SpatialPartitioner.scala
  src/test/scala/com/spark3d/geometryObjects/BoxEnvelopeTest.scala
  src/test/scala/com/spark3d/geometryObjects/Point3DTest.scala
  src/test/scala/com/spark3d/geometryObjects/Shape3DTest.scala
  src/test/scala/com/spark3d/geometryObjects/ShellEnvelopeTest.scala
  src/test/scala/com/spark3d/geometryObjects/SphereTest.scala
  src/test/scala/com/spark3d/serialization/Spark3dRegistratorTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreePartitionerTest.scala
  src/test/scala/com/spark3d/spatialPartitioning/OctreeTest.scala
Labels: JTS replacement, code cleaning

#50 Window query
  src/main/scala/com/spark3d/geometryObjects/BoxEnvelope.scala
  src/main/scala/com/spark3d/geometryObjects/Point3D.scala
  src/main/scala/com/spark3d/geometryObjects/Shape3D.scala
  src/main/scala/com/spark3d/geometryObjects/ShellEnvelope.scala
  src/main/scala/com/spark3d/spatialOperator/RangeQuery.scala
  src/main/scala/com/spark3d/utils/Utils.scala
  src/test/scala/com/spark3d/geometryObjects/BoxEnvelopeTest.scala
  src/test/scala/com/spark3d/geometryObjects/Point3DTest.scala
  src/test/scala/com/spark3d/geometryObjects/ShellEnvelopeTest.scala
  src/test/scala/com/spark3d/spatialOperator/CenterCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/PixelCrossMatchTest.scala
  src/test/scala/com/spark3d/spatialOperator/RangeQueryTest.scala
  src/test/scala/com/spark3d/utils/UtilsTest.scala
Labels: 3D methods, enhancement

#52 Update the tutorials: Add windowQuery, and re-write the Xmatch tuto
  .travis.yml
  build.sbt
  docs/02_introduction.md
  docs/03_partitioning.md
  docs/04_query.md
  docs/about.md
  docs/assets/images/BoxMatch.png
  docs/assets/images/sphereMatch.png
Labels: website

#57 Update partitioning tutorial with Octree
  docs/03_partitioning.md
Labels: documentation, website

#58 Speed-up cross-match methods by using native Scala methods
  src/main/scala/com/spark3d/spatialOperator/CenterCrossMatch.scala
  src/main/scala/com/spark3d/spatialOperator/PixelCrossMatch.scala
Labels: 3D methods, code cleaning, enhancement
